### PR TITLE
Add Labrada

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello @Omnibus-Type!

Here you can find the changes I did, according the GF specs. 
I didn't change much, the file was clean, thanks for that :) 
I just modified the Radical sign and the quotes, which had interpolation problems.
Capture d’écran 2023-01-11 à 11 52 57

### I have some questions / remarks though:
- Copyright: in the OFL it was at 2022 and in the glyphs file at 2019. I left it at 2022, let me know if it needs to be changed.
- Usually for v-metrics, the total height should be around 120%/130% (for example, if UPM is 1000, typoAscender+typoDescender = 1200). Here we have 145%, which gives a pretty wide line spacing. Is this ok for you?
Capture d’écran 2023-01-11 à 13 58 52

- The Germandbls is missing, you can add it if you want, but if it does not appear in the glyphset it is not a big deal
- The ellipsis and period in upright is different from the italic. Is it voluntary? (in the thin master)
Capture d’écran 2023-01-11 à 14 04 50

Don't hesitate if you have any questions. 
If there are some things to modify, I'll add commits to this PR, so you can wait before merging.
thank you!

Emma

### CODE REVIEW

**Comment by emmamarichal** [comment]
Hi @Omnibus-Type, have you seen this PR? What do you think about it?
Don't hesitate if you need anything,
Cheers!

**Comment by Omnibus-Type** [comment]
Hi @emmamarichal! We had not seen it... I'm sorry! 
We'll review it and then we'll answer you right here. Thanks!

**Comment by emmamarichal** [comment]
@Omnibus-Typen thanks for merging!
Will you change the ellipsis/period thing I mentioned above? or can I start the onboarding process?

**Comment by Omnibus-Type** [comment]
@emmamarichal please start the onboarding process... Thanks in advance!

**Pull request merged**
